version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blog7092BackendUser
      POSTGRES_PASSWORD: blog7092BackendPass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: blog
    hostname: postgres
    restart: always
    user: root
